spring:
  datasource:
    url: jdbc:h2:~/openweather;AUTO_SERVER=TRUE
    username: sa
    password: sa
  data:
    mongodb:
      uri: mongodb://mongo:27017/test
      #uri: mongodb://localhost:27017/test #For local use only
  jpa:
    show-sql: true

server:
  port: 8086

openweather:
  api:
    baseurl: http://api.openweathermap.org/data/2.5
    key: API_KEY