spring:
  datasource:
    url: jdbc:h2:~/openweather;AUTO_SERVER=TRUE
  jpa:
    show-sql: true

server:
  port: 8086

openweather:
  api:
    baseurl: http://api.openweathermap.org/data/2.5
    key: API_KEY