spring:
  datasource:
    url: jdbc:h2:~/openweather;AUTO_SERVER=TRUE
  data:
    mongodb:
      #uri: mongodb://mongo:27017/test
      uri: mongodb://localhost:27017/test
  jpa:
    show-sql: true

server:
  port: 8086

openweather:
  api:
    baseurl: http://api.openweathermap.org/data/2.5
    key: eb8b1a9405e659b2ffc78f0a520b1a46